### ISSUE TITLE
Change active watcher flush for latest vue-next RC compliance

### ISSUE THREAD

**Issue by AlexandreBonaventure** [posva/focus-trap-vue#289]
As per https://github.com/vuejs/vue-next/commit/49bb44756fda0a7019c69f2fa6b880d9e41125aa watcher flush got changed. This library is affected, although not in all cases. I'll update the test cases soon to prove my point.

**Comment by posva** [comment]
okay, thanks! I push forced to remove the redundant commits BTW

**Comment by AlexandreBonaventure** [comment]
@posva I've updated the App example to illustrate the issue when you wrap a transitioning element here: https://github.com/posva/focus-trap-vue/tree/flush-post. 
Because of the `pre` flush the el ref at this point is still a `v-if` comment node. the focus-trap will then throw an error. 

If that's good for you I'll update the flush option to `post` in the next branch

**Comment by posva** [comment]
Sure! I had to update similar things in other places! Let me know when it's done and I will release a version

**Comment by AlexandreBonaventure** [comment]
@posva done ! thank you

**Comment by posva** [comment]
Okay, I will rebase history and push force again. The pull request should have been squashed but I forgot to tell you 😅

**Comment by AlexandreBonaventure** [comment]
sounds good, I'll remember for the next time

**Comment by posva** [comment]
yeah, I don't think I will spend the time to rebase this one... Too many things

**Comment by AlexandreBonaventure** [comment]
it is the updated test case (it was failing for transitioning components not the other regular cases). We don't really test it yet but at least in the future we know this case should be supported

**Comment by posva** [comment]
Ah, that's what I thought, can you add an e2e test too for the use case, please?

**Comment by posva** [comment]
Let me know when you add it so I can release a version

**Comment by AlexandreBonaventure** [comment]
@posva good to go! I've updated tests. No perfect but I feel like it is good enough

**Comment by posva** [comment]
Published!
