### ISSUE TITLE
Vue3 compatible version no longer exports `activate` and `deactivate` methods

### ISSUE THREAD

**Issue by DV8FromTheWorld** [posva/focus-trap-vue#374]
In the Vue2 version (`1.x`) the following was valid:
```vue
<template>
  <FocusTrap ref="focusTrap">
    <!-- Content here -->
  </FocusTrap>
</template>

<script>
export default {
  methods: {
    manuallyDeactivate() {
      this.$refs.focusTrap.deactivate()
    }
  }
} 
</script>
```
The [`activate` and `deactivate` methods were exposed](https://github.com/posva/focus-trap-vue/blob/master/src/FocusTrap.ts#L109-L118) on the component. The [documentation](https://github.com/posva/focus-trap-vue#methods) speaks to their usage as well.

This is no longer possible in the Vue3 (2.x / 3.x) version as the methods are not being exposed on the component.

**Comment by posva** [comment]
You might need to do `this.$refs.focusTrap.proxy.deactivate()`

**Comment by DV8FromTheWorld** [comment]
Gave that a shot but it didn't work.

**Comment by posva** [comment]
Ah right, we need https://github.com/vuejs/rfcs/pull/210
