### ISSUE TITLE
Enhancement - preventScroll option

### ISSUE THREAD

**Issue by Delicious-Bacon** [posva/focus-trap-vue#384]
### What problem is this solving

Prevents scroll jumps when focusing both `<focus-trap>` target HTMLElement and `returnFocusOnDeactivate` target HTMLElement.

### Proposed solution

Implement what original `focus-trap` library uses (`preventScroll` create option and `tryFocus` function):

[focus-trap's `preventScroll` create option](https://github.com/focus-trap/focus-trap#createoptions)

[focus-trap's `tryFocus` function](https://github.com/focus-trap/focus-trap/blob/b58f5efddd0deb246826a88a9d31c41ab7b99029/index.js#L253)

We should have a `tryFocus` function called that passes `preventScroll: true` as `FocusOptions` in `HTMLElement.focus(FocusOptions)` method when focusing target HTMLElements.

### Describe alternatives you've considered

There are ways to dodge scrolling issues, but it would require using `position: fixed` on target HTMLElements.

**Comment by posva** [comment]
I think it should just accept all the possible options for focus-trap

**Comment by Delicious-Bacon** [comment]
> I think it should just accept all the possible options for focus-trap

Sure, that sounds better than implementing something anew!

As far as I'm aware, there is no `preventScroll` `prop` at this moment:
[props](https://github.com/posva/focus-trap-vue/blob/main/src/FocusTrap.ts#L19)

**Comment by miller-kevin** [comment]
Any plans to add this @posva ? As @Delicious-Bacon said, it's not a prop in the vue version 
<img width="275" alt="image" src="https://user-images.githubusercontent.com/50149901/152064664-f2558a4c-7df7-4e88-9de9-1f4ad6560243.png">

**Comment by miller-kevin** [comment]
@posva Thanks for addressing this. Any idea when the next release will be?
