### ISSUE TITLE
el.querySelectorAll is not a function when el is a Vue component Proxy

### ISSUE THREAD

**Issue by japorized** [posva/focus-trap-vue#385]
Hello and thank you for working on this package. I noticed a potential bug related to #380. Here's a description of the issue.

### Context

Whenever the focus trap becomes active, and the sole element in the focus trap is another Vue component (at least that seems to be the case), an error will be thrown in the console.

### Reproduction

I've created a [CodeSandbox instance](https://codesandbox.io/s/little-frost-c4don?file=/src/App.vue) where you can see the behavior for yourself.

### Steps to reproduce the behavior

1. Click on the "Toggle trap focus" button
2. See error

### Expected behavior

Focus trap should kick in as the `active` prop is set to `true`.

### Actual behavior

Received the following error when setting the `active` prop to `true`.
```
index.js:25 Uncaught (in promise) TypeError: el.querySelectorAll is not a function
    at getCandidates2 (index.js:25)
    at tabbable2 (index.js:243)
    at index.js:226
    at Array.map (<anonymous>)
    at updateTabbableNodes2 (index.js:225)
    at Object.activate (index.js:546)
    at watch.immediate (focus-trap-vue.esm-bundler.js:80)
    at callWithErrorHandling (runtime-core.esm-bundler.js:154)
    at callWithAsyncErrorHandling (runtime-core.esm-bundler.js:163)
    at job (runtime-core.esm-bundler.js:2096)
```

### Additional information

I first discovered this issue on Electron, and did a little debugging there to look at what `el` is. It turns out when the element inside of `<focus-trap>` is a Vue component, instead of an `HTMLElement`, a `Proxy` of the Vue component is passed.

For clarity, I tried changing the element in the focus trap to a regular `<div>` and it worked as you'd expect.

**Nov 12th, 2021**
Dug a bit deeper to understand a bit more about the dependencies here.
The error is thrown from [`tabbable`](https://github.com/focus-trap/tabbable), which is a dependency of [`focus-trap`](https://github.com/focus-trap/focus-trap), of which this library depends on. Looks like `focus-trap` is a expected to work in a framework-less scenario.

A bit more digging shows that this library is using the `as` keyword in TypeScript [on line 65 in the `FocusTrap.ts` file](https://github.com/posva/focus-trap-vue/blob/main/src/FocusTrap.ts#L65). Pasting that block here for context:
```ts
   const el = ref<HTMLElement | null>(null)

    const ensureTrap = () => {
      if (trap) {
        return
      }

      const { initialFocus } = props
      trap = createFocusTrap(el.value as HTMLElement, {
```

I'm not familiar with Vue's API for plugins but if I understand it correctly, `el` is set during render, particularly [on line 143 in the same file](https://github.com/posva/focus-trap-vue/blob/dbec7508465e2bc9c42a3001ad87058a12d6d921/src/FocusTrap.ts#L143)?

**Nov 13th, 2021**
Cloned the repo to try see if I can figure something out.

I'm away from my computer now, but when I tried earlier, I was able to "fix" the issue. I'm not sure if it's the right thing to do, however.

First, I added the `ComponentPublicInstance` type (from `vue`) to the union for `el`.

Then I added an extra check before `createFocusTrap` is called, like so
```typescript
  if (
    !(el instanceof HTMLElement) &&
    Reflect.has(el.value, "$el")
  ) {
    el.value = (el.value as ComponentPublicInstance).$el;
  }

  trap = createFocusTrap(el.value as HTMLElement, {
```

However, one thing that's notable is that `$el` has type `any` within `ComponentPublicInstance`, not `HTMLElement`. Hence why I'm not sure if this is a good solution.

I'll likely check things out a bit further, get a bit more guarantee in before I make a PR.

---

Related issues found: #380

**Comment by kyrylo93** [comment]
Hi, any updates?

**Comment by japorized** [comment]
Hi @kyrylo93. #387 was made in an attempt to fix this. It'll be up to @posva to give the final approval, but it can definitely use some scrutiny from anyone with an interest in this issue.

**Comment by sebaguse** [comment]
Hi, is there any update on this issue, please?

**Comment by japorized** [comment]
posva seems to be busy and so responses on the PR has been slow. I would definitely welcome anyone to just take a look at the PR and provide suggestions there. There are just a few more (I think) difficulties in making sure the right types are being set and passed around. I am, unfortunately, a little too in the dark about what the author envisions the data flow to be like.

In the meantime, if you're unsure about how to help but want to work around the issue, try to use the library by only wrapping around native HTML elements and not Vue elements. I understand that it's not ideal or always possible, however.
