### ISSUE TITLE
Missing ending apostrophe on readme section of npmjs.com homepage for forcus-trap-vue

### ISSUE THREAD

**Issue by outdoorsman** [posva/focus-trap-vue#501]
### Reproduction

Just visit the page https://www.npmjs.com/package/focus-trap-vue, and change `.mount('#app)` to be `.mount('#app')`. There's just a missing ending single apostrophe. It looks like it correct in your README.md but not on npmjs.com.

**Comment by posva** [comment]
Thanks! Next time just open the pull request directly 😄

**Comment by outdoorsman** [comment]
@posva I would be happy to submit a pull request, but didn't know which file is responsible for the npmjs.com homepage content. I assumed it would have been README.md, but it's not an issue there.

**Comment by posva** [comment]
You actually already opened the PR https://github.com/posva/focus-trap-vue/pull/480 😅 
As you can imagine, I won't be releasing a new version for a typo on the readme

**Comment by outdoorsman** [comment]
Dohhh... didn't look through the commits and totally forgot about that. Okay makes sense now ha ha.
